In [22]:
import pandas as pd
import numpy as np
import tensorflow as ft
from tensorflow import keras

In [23]:
df = pd.read_csv('1_boston_housing.csv')
df

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,b,lstat,MEDV
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0,0.573,6.593,69.1,2.4786,1,273,21.0,391.99,9.67,22.4
502,0.04527,0.0,11.93,0,0.573,6.120,76.7,2.2875,1,273,21.0,396.90,9.08,20.6
503,0.06076,0.0,11.93,0,0.573,6.976,91.0,2.1675,1,273,21.0,396.90,5.64,23.9
504,0.10959,0.0,11.93,0,0.573,6.794,89.3,2.3889,1,273,21.0,393.45,6.48,22.0
505,0.04741,0.0,11.93,0,0.573,6.030,80.8,2.5050,1,273,21.0,396.90,7.88,11.9

In [24]:
df.isnull().sum().count()

14

In [25]:
df.dropna()

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,b,lstat,MEDV
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0,0.573,6.593,69.1,2.4786,1,273,21.0,391.99,9.67,22.4
502,0.04527,0.0,11.93,0,0.573,6.120,76.7,2.2875,1,273,21.0,396.90,9.08,20.6
503,0.06076,0.0,11.93,0,0.573,6.976,91.0,2.1675,1,273,21.0,396.90,5.64,23.9
504,0.10959,0.0,11.93,0,0.573,6.794,89.3,2.3889,1,273,21.0,393.45,6.48,22.0
505,0.04741,0.0,11.93,0,0.573,6.030,80.8,2.5050,1,273,21.0,396.90,7.88,11.9

In [26]:
x=df[["crim","zn","indus","chas","nox","rm","age","dis","rad","tax","ptratio","b","lstat"]]
x

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,b,lstat
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33
...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0,0.573,6.593,69.1,2.4786,1,273,21.0,391.99,9.67
502,0.04527,0.0,11.93,0,0.573,6.120,76.7,2.2875,1,273,21.0,396.90,9.08
503,0.06076,0.0,11.93,0,0.573,6.976,91.0,2.1675,1,273,21.0,396.90,5.64
504,0.10959,0.0,11.93,0,0.573,6.794,89.3,2.3889,1,273,21.0,393.45,6.48
505,0.04741,0.0,11.93,0,0.573,6.030,80.8,2.5050,1,273,21.0,396.90,7.88

In [27]:
y = df[['MEDV']]
y.head()

   MEDV
0  24.0
1  21.6
2  34.7
3  33.4
4  36.2

In [28]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
pp = MinMaxScaler()

In [29]:
x_scaled = pp.fit_transform(x)
x_scaled

array([[0.00000000e+00, 1.80000000e-01, 6.78152493e-02, ...,
        2.87234043e-01, 1.00000000e+00, 8.96799117e-02],
       [2.35922539e-04, 0.00000000e+00, 2.42302053e-01, ...,
        5.53191489e-01, 1.00000000e+00, 2.04470199e-01],
       [2.35697744e-04, 0.00000000e+00, 2.42302053e-01, ...,
        5.53191489e-01, 9.89737254e-01, 6.34657837e-02],
       ...,
       [6.11892474e-04, 0.00000000e+00, 4.20454545e-01, ...,
        8.93617021e-01, 1.00000000e+00, 1.07891832e-01],
       [1.16072990e-03, 0.00000000e+00, 4.20454545e-01, ...,
        8.93617021e-01, 9.91300620e-01, 1.31070640e-01],
       [4.61841693e-04, 0.00000000e+00, 4.20454545e-01, ...,
        8.93617021e-01, 1.00000000e+00, 1.69701987e-01]])

In [31]:
x_train,x_test,y_train,y_test = train_test_split(x_scaled,y,test_size=0.2)

In [32]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Flatten,Dense
model = Sequential()

In [33]:
model.add(Dense(128,activation='relu'))
model.add(Dense(64,activation='relu'))
model.add(Dense(1,activation='linear'))

In [34]:
model.summary

In [35]:
model.compile(optimizer='adam',loss='mse',metrics=['mae'])

In [36]:
model.fit(x_scaled,y,epochs=100)

Epoch 1/100
16/16 [==============================] - 2s 6ms/step - loss: 554.5804 - mae: 21.6642
Epoch 2/100
16/16 [==============================] - 0s 6ms/step - loss: 466.0864 - mae: 19.3533
Epoch 3/100
16/16 [==============================] - 0s 6ms/step - loss: 324.1127 - mae: 15.1398
Epoch 4/100
16/16 [==============================] - 0s 6ms/step - loss: 174.7074 - mae: 10.4333
Epoch 5/100
16/16 [==============================] - 0s 6ms/step - loss: 128.4065 - mae: 8.8179
Epoch 6/100
16/16 [==============================] - 0s 6ms/step - loss: 107.5130 - mae: 7.8927
Epoch 7/100
16/16 [==============================] - 0s 6ms/step - loss: 89.5261 - mae: 7.0275
Epoch 8/100
16/16 [==============================] - 0s 6ms/step - loss: 76.8355 - mae: 6.4250
Epoch 9/100
16/16 [==============================] - 0s 7ms/step - loss: 66.6689 - mae: 6.0101
Epoch 10/100
16/16 [==============================] - 0s 6ms/step - loss: 59.2500 - mae: 5.4551
Epoch 11/100
16/16 [==============================] - 0s 8ms/step - loss: 54.1300 - mae: 5.2479
Epoch 12/100
16/16 [==============================] - 0s 7ms/step - loss: 51.1763 - mae: 5.0808
Epoch 13/100
16/16 [==============================] - 0s 7ms/step - loss: 48.5101 - mae: 4.9671
Epoch 14/100
16/16 [==============================] - 0s 7ms/step - loss: 45.9794 - mae: 4.7678
Epoch 15/100
16/16 [==============================] - 0s 6ms/step - loss: 43.7240 - mae: 4.6760
Epoch 16/100
16/16 [==============================] - 0s 7ms/step - loss: 41.4565 - mae: 4.5428
Epoch 17/100
16/16 [==============================] - 0s 6ms/step - loss: 39.5539 - mae: 4.3971
Epoch 18/100
16/16 [==============================] - 0s 6ms/step - loss: 37.6146 - mae: 4.3078
Epoch 19/100
16/16 [==============================] - 0s 6ms/step - loss: 35.6662 - mae: 4.2513
Epoch 20/100
16/16 [==============================] - 0s 5ms/step - loss: 33.9151 - mae: 4.1294
Epoch 21/100
16/16 [==============================] - 0s 6ms/step - loss: 32.1941 - mae: 3.8915
Epoch 22/100
16/16 [==============================] - 0s 6ms/step - loss: 30.4537 - mae: 3.9403
Epoch 23/100
16/16 [==============================] - 0s 7ms/step - loss: 28.8244 - mae: 3.7409
Epoch 24/100
16/16 [==============================] - 0s 6ms/step - loss: 27.4845 - mae: 3.6238
Epoch 25/100
16/16 [==============================] - 0s 6ms/step - loss: 26.4817 - mae: 3.6090
Epoch 26/100
16/16 [==============================] - 0s 6ms/step - loss: 25.1594 - mae: 3.4268
Epoch 27/100
16/16 [==============================] - 0s 7ms/step - loss: 24.4306 - mae: 3.3814
Epoch 28/100
16/16 [==============================] - 0s 9ms/step - loss: 23.4016 - mae: 3.3958
Epoch 29/100
16/16 [==============================] - 0s 5ms/step - loss: 22.5792 - mae: 3.2365
Epoch 30/100
16/16 [==============================] - 0s 4ms/step - loss: 21.8947 - mae: 3.2245
Epoch 31/100
16/16 [==============================] - 0s 4ms/step - loss: 21.4928 - mae: 3.1392
Epoch 32/100
16/16 [==============================] - 0s 4ms/step - loss: 20.9314 - mae: 3.1795
Epoch 33/100
16/16 [==============================] - 0s 6ms/step - loss: 20.9163 - mae: 3.0691
Epoch 34/100
16/16 [==============================] - 0s 5ms/step - loss: 20.2581 - mae: 3.1472
Epoch 35/100
16/16 [==============================] - 0s 4ms/step - loss: 19.9704 - mae: 3.0149
Epoch 36/100
16/16 [==============================] - 0s 4ms/step - loss: 19.4797 - mae: 3.0416
Epoch 37/100
16/16 [==============================] - 0s 7ms/step - loss: 19.6307 - mae: 2.9873
Epoch 38/100
16/16 [==============================] - 0s 8ms/step - loss: 19.3657 - mae: 3.0129
Epoch 39/100
16/16 [==============================] - 0s 8ms/step - loss: 19.2990 - mae: 2.9687
Epoch 40/100
16/16 [==============================] - 0s 8ms/step - loss: 18.6173 - mae: 2.9115
Epoch 41/100
16/16 [==============================] - 0s 8ms/step - loss: 18.5875 - mae: 2.9241
Epoch 42/100
16/16 [==============================] - 0s 9ms/step - loss: 18.3203 - mae: 2.9334
Epoch 43/100
16/16 [==============================] - 0s 7ms/step - loss: 18.0618 - mae: 2.8918
Epoch 44/100
16/16 [==============================] - 0s 7ms/step - loss: 17.8535 - mae: 2.8660
Epoch 45/100
16/16 [==============================] - 0s 7ms/step - loss: 18.2968 - mae: 2.9690
Epoch 46/100
16/16 [==============================] - 0s 7ms/step - loss: 17.8717 - mae: 2.8743
Epoch 47/100
16/16 [==============================] - 0s 6ms/step - loss: 17.5744 - mae: 2.8564
Epoch 48/100
16/16 [==============================] - 0s 7ms/step - loss: 17.5173 - mae: 2.8007
Epoch 49/100
16/16 [==============================] - 0s 6ms/step - loss: 17.2519 - mae: 2.8606
Epoch 50/100
16/16 [==============================] - 0s 7ms/step - loss: 16.9938 - mae: 2.7882
Epoch 51/100
16/16 [==============================] - 0s 6ms/step - loss: 17.0207 - mae: 2.7745
Epoch 52/100
16/16 [==============================] - 0s 7ms/step - loss: 16.6967 - mae: 2.7851
Epoch 53/100
16/16 [==============================] - 0s 6ms/step - loss: 16.5698 - mae: 2.7735
Epoch 54/100
16/16 [==============================] - 0s 6ms/step - loss: 16.1753 - mae: 2.7363
Epoch 55/100
16/16 [==============================] - 0s 6ms/step - loss: 16.1179 - mae: 2.7286
Epoch 56/100
16/16 [==============================] - 0s 7ms/step - loss: 16.2962 - mae: 2.7740
Epoch 57/100
16/16 [==============================] - 0s 9ms/step - loss: 16.4695 - mae: 2.7408
Epoch 58/100
16/16 [==============================] - 0s 3ms/step - loss: 15.9530 - mae: 2.7568
Epoch 59/100
16/16 [==============================] - 0s 2ms/step - loss: 16.3288 - mae: 2.7929
Epoch 60/100
16/16 [==============================] - 0s 4ms/step - loss: 15.4411 - mae: 2.6298
Epoch 61/100
16/16 [==============================] - 0s 7ms/step - loss: 15.3200 - mae: 2.6449
Epoch 62/100
16/16 [==============================] - 0s 8ms/step - loss: 15.0722 - mae: 2.6400
Epoch 63/100
16/16 [==============================] - 0s 7ms/step - loss: 14.9797 - mae: 2.6085
Epoch 64/100
16/16 [==============================] - 0s 3ms/step - loss: 14.7537 - mae: 2.6499
Epoch 65/100
16/16 [==============================] - 0s 3ms/step - loss: 14.7949 - mae: 2.5999
Epoch 66/100
16/16 [==============================] - 0s 3ms/step - loss: 14.7977 - mae: 2.5988
Epoch 67/100
16/16 [==============================] - 0s 3ms/step - loss: 14.6863 - mae: 2.6060
Epoch 68/100
16/16 [==============================] - 0s 3ms/step - loss: 14.2891 - mae: 2.5559
Epoch 69/100
16/16 [==============================] - 0s 4ms/step - loss: 14.1089 - mae: 2.5990
Epoch 70/100
16/16 [==============================] - 0s 4ms/step - loss: 14.2294 - mae: 2.5496
Epoch 71/100
16/16 [==============================] - 0s 3ms/step - loss: 13.7326 - mae: 2.5168
Epoch 72/100
16/16 [==============================] - 0s 6ms/step - loss: 13.7153 - mae: 2.5043
Epoch 73/100
16/16 [==============================] - 0s 6ms/step - loss: 13.9538 - mae: 2.5413
Epoch 74/100
16/16 [==============================] - 0s 6ms/step - loss: 13.3572 - mae: 2.5424
Epoch 75/100
16/16 [==============================] - 0s 6ms/step - loss: 13.6421 - mae: 2.5130
Epoch 76/100
16/16 [==============================] - 0s 6ms/step - loss: 14.0704 - mae: 2.5774
Epoch 77/100
16/16 [==============================] - 0s 6ms/step - loss: 13.4698 - mae: 2.6160
Epoch 78/100
16/16 [==============================] - 0s 5ms/step - loss: 13.3401 - mae: 2.5221
Epoch 79/100
16/16 [==============================] - 0s 3ms/step - loss: 13.1151 - mae: 2.4513
Epoch 80/100
16/16 [==============================] - 0s 3ms/step - loss: 13.0595 - mae: 2.4764
Epoch 81/100
16/16 [==============================] - 0s 3ms/step - loss: 12.7152 - mae: 2.4669
Epoch 82/100
16/16 [==============================] - 0s 5ms/step - loss: 12.4556 - mae: 2.4179
Epoch 83/100
16/16 [==============================] - 0s 7ms/step - loss: 12.3483 - mae: 2.4155
Epoch 84/100
16/16 [==============================] - 0s 7ms/step - loss: 12.2509 - mae: 2.3939
Epoch 85/100
16/16 [==============================] - 0s 7ms/step - loss: 12.3603 - mae: 2.4643
Epoch 86/100
16/16 [==============================] - 0s 7ms/step - loss: 12.7917 - mae: 2.5024
Epoch 87/100
16/16 [==============================] - 0s 7ms/step - loss: 12.2724 - mae: 2.4023
Epoch 88/100
16/16 [==============================] - 0s 6ms/step - loss: 12.0666 - mae: 2.4136
Epoch 89/100
16/16 [==============================] - 0s 6ms/step - loss: 11.8314 - mae: 2.3899
Epoch 90/100
16/16 [==============================] - 0s 7ms/step - loss: 11.8660 - mae: 2.3616
Epoch 91/100
16/16 [==============================] - 0s 5ms/step - loss: 11.8312 - mae: 2.3368
Epoch 92/100
16/16 [==============================] - 0s 3ms/step - loss: 11.6634 - mae: 2.3859
Epoch 93/100
16/16 [==============================] - 0s 4ms/step - loss: 11.4427 - mae: 2.3255
Epoch 94/100
16/16 [==============================] - 0s 4ms/step - loss: 11.5257 - mae: 2.3537
Epoch 95/100
16/16 [==============================] - 0s 7ms/step - loss: 11.4598 - mae: 2.3730
Epoch 96/100
16/16 [==============================] - 0s 6ms/step - loss: 11.2912 - mae: 2.3108
Epoch 97/100
16/16 [==============================] - 0s 7ms/step - loss: 11.1633 - mae: 2.3067
Epoch 98/100
16/16 [==============================] - 0s 6ms/step - loss: 11.1255 - mae: 2.3276
Epoch 99/100
16/16 [==============================] - 0s 8ms/step - loss: 11.1845 - mae: 2.3048
Epoch 100/100
16/16 [==============================] - 0s 6ms/step - loss: 10.9912 - mae: 2.2818

In [37]:
mse,mae = model.evaluate(x_test,y_test)

4/4 [==============================] - 0s 5ms/step - loss: 15.6853 - mae: 2.5453

In [38]:
print(mse)

15.685279846191406

In [39]:
print(mae)

2.5453078746795654